import { useEffect, useRef, useState } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { ArrowUpRight, ArrowRight, Search, X, Menu, UserRound, ChevronDown, ChevronRight, MapPin, ExternalLink, Sun, Zap, Leaf } from 'lucide-react'
import type { SiteRoute } from './types'
import { siteRoutes } from './routes'
import { base, solutions, tasks, guides } from './content'
import './styles/site.css'

const media = { hero: '/assets/images/hero-lausanne-sil.jpg', solar: '/assets/images/solaire-photovoltaique.jpg', city: '/assets/images/lausanne-pierre-de-plan.jpg' }
const sourceMap: Record<string, string> = {
  home: `${base}.html`, electricite: `${base}/particuliers/je-choisis-mon-offre/electricite.html`,
  chaleur: `${base}/particuliers/je-choisis-mon-offre/chaleur.html`, gaz: `${base}/particuliers/je-choisis-mon-offre/gaz-naturel.html`,
  multimedia: `${base}/particuliers/je-choisis-mon-offre/multimedia.html`, mobilite: `${base}/particuliers/je-choisis-mon-offre/mobilite.html`,
  solaire: `${base}/particuliers/je-produis-mon-energie/solaire-photovoltaique.html`, demenagement: `${base}/particuliers/mon-compte/demenagement.html`,
  contact: `${base}/particuliers/contact-sil.html`, 'les-sil': `${base}/a-propos-sil.html`, carriere: `${base}/a-propos-sil/c-for.html`,
  'economies-energie': `${base}/particuliers/j-optimise-ma-consommation/renovation-de-mon-bien-immobilier.html`,
}
function Source({ id }: { id: string }) { return <div className="source-note"><span>Pour aller plus loin</span><a href={sourceMap[id] || base}>Consulter les informations officielles des SiL <ExternalLink size={14}/></a></div> }
function ButtonLink({ to, children, light = false }: { to: string; children: React.ReactNode; light?: boolean }) { return <Link className={`button ${light ? 'button-light' : ''}`} to={to}>{children}<ArrowUpRight size={18}/></Link> }
function Header() {
  const [open, setOpen] = useState<string | null>(null)
  const [search, setSearch] = useState(false)
  const [query, setQuery] = useState('')
  const location = useLocation()
  const header = useRef<HTMLElement>(null)
  useEffect(() => { setOpen(null); setSearch(false); setQuery(''); window.scrollTo(0, 0) }, [location.pathname])
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { const menuWasOpen = open === 'mobile'; setOpen(null); setSearch(false); if (menuWasOpen) requestAnimationFrame(() => header.current?.querySelector<HTMLButtonElement>('.mobile-toggle')?.focus()) } }; const outside = (event: MouseEvent) => { if (!header.current?.contains(event.target as Node)) { setOpen(null); setSearch(false) } }; document.addEventListener('keydown', close); document.addEventListener('mousedown', outside); return () => { document.removeEventListener('keydown', close); document.removeEventListener('mousedown', outside) } }, [open])
  const groups = [{ id: 'energies', label: 'Énergies & solutions', path: '/energies-solutions' }, { id: 'demarches', label: 'Vos démarches', path: '/vos-demarches' }, { id: 'institution', label: 'Les SiL', path: '/les-sil' }]
  const results = siteRoutes.filter(r => r.path !== '/' && `${r.label} ${r.description}`.toLocaleLowerCase('fr').normalize('NFD').replace(/[\u0300-\u036f]/g, '').includes(query.toLocaleLowerCase('fr').normalize('NFD').replace(/[\u0300-\u036f]/g, '')))
  return <header ref={header} className="site-header"><div className="utility"><div className="container utility-inner"><span>Un service de la Ville de Lausanne</span><div><Link to="/depannage-urgences">Dépannage & urgences</Link><span className="utility-divider"/><Link to="/contact">Contact</Link><span className="language">FR</span></div></div></div><div className="container nav-row"><Link to="/" className="brand" aria-label="SiL — Accueil"><img src="/assets/brand/logo-sil.svg" alt="SiL"/><span>Services industriels<br/>de Lausanne</span></Link><nav className="desktop-nav" aria-label="Navigation principale">{groups.map(g => <button key={g.id} onClick={() => { setOpen(open === g.id ? null : g.id); setSearch(false) }} aria-expanded={open === g.id} className={open === g.id ? 'active' : ''}>{g.label}<ChevronDown size={14}/></button>)}</nav><div className="nav-actions"><button className="icon-button" aria-label="Rechercher" aria-expanded={search} onClick={() => {setSearch(!search); setOpen(null)}}>{search ? <X size={22}/> : <Search size={22}/>}</button><Link className="account-link" to="/facturation-paiement"><UserRound size={17}/><span>Mon espace</span><ArrowUpRight size={15}/></Link><button className="icon-button mobile-toggle" aria-label={open === 'mobile' ? 'Fermer le menu' : 'Ouvrir le menu'} aria-expanded={open === 'mobile'} onClick={() => {setOpen(open === 'mobile' ? null : 'mobile'); setSearch(false)}}>{open === 'mobile' ? <X/> : <Menu/>}</button></div></div>
  {open && <div className="menu-panel"><div className="container menu-grid">{groups.filter(g => open === 'mobile' || open === g.id).map(g => <div key={g.id}><Link className="menu-heading" to={g.path}>{g.label}<ArrowUpRight size={20}/></Link><div className="menu-links">{siteRoutes.filter(r => r.group === g.id && r.path !== '/' && r.path !== g.path && r.showInNavigation !== false).map(r => <Link key={r.id} to={r.path}>{r.label}<ArrowRight size={15}/></Link>)}</div></div>)}</div></div>}
  {search && <div className="search-panel"><div className="container"><label htmlFor="site-search">Que recherchez-vous ?</label><div className="search-input"><Search/><input autoFocus id="site-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Une offre, une démarche, un contact…"/></div><div className="search-results">{results.slice(0, 8).map(r => <Link to={r.path} key={r.id}>{r.label}<ArrowUpRight size={17}/></Link>)}{results.length === 0 && <p>Aucun résultat. Essayez « électricité », « facture » ou « contact ».</p>}</div></div></div>}
  </header>
}
function Footer() { return <footer><div className="container"><div className="footer-top"><div><img className="footer-logo" src="/assets/brand/logo-sil.svg" alt="SiL"/><h2>L’énergie d’ici.<br/>La vie, ensemble.</h2><p>Services industriels de Lausanne<br/>Place Chauderon 23<br/>1003 Lausanne</p></div><div className="footer-links"><div><h3>Énergies & solutions</h3>{solutions.map(s => <Link key={s.id} to={`/${s.id}`}>{s.label}</Link>)}</div><div><h3>À votre service</h3>{tasks.map(t => <Link key={t.id} to={`/${t.id}`}>{t.label}</Link>)}<Link to="/depannage-urgences">Dépannage & urgences</Link></div><div><h3>Les SiL</h3><Link to="/les-sil">Qui sommes-nous ?</Link><Link to="/economies-energie">Économies d’énergie</Link><Link to="/actualites">À découvrir</Link><Link to="/carriere">Carrières & formation</Link><a href={base}>Site officiel <ArrowUpRight size={13}/></a></div></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Services industriels de Lausanne</span><Link to="/mentions-legales">À propos du prototype & sources</Link><span>Lausanne, naturellement.</span></div></div></footer> }
function ContactBanner() { return <section className="contact-banner container"><div><span className="eyebrow">Toujours à vos côtés</span><h2>Une question, un projet ?<br/>Parlons-en.</h2></div><div><p>Une équipe proche de vous,<br/>pour trouver la bonne solution.</p><ButtonLink to="/contact">Nous contacter</ButtonLink></div></section> }
function SolutionGrid() { return <div className="solutions-grid">{solutions.map((s, index) => <Link to={`/${s.id}`} key={s.id} className={`solution-card ${s.color}`}><div className="solution-card-top"><s.icon size={30} strokeWidth={1.4}/><span>0{index + 1}</span></div><div><h3>{s.label}</h3><p>{s.description}</p></div><ArrowUpRight className="card-arrow" size={24}/></Link>)}</div> }
function Home() { return <><section className="hero container"><div className="hero-copy"><span className="eyebrow"><span className="red-line"/>L’énergie de Lausanne</span><h1>La vie avance.<br/>L’énergie<br/><span>aussi.</span></h1><p>Chaque jour à vos côtés. Pour vous connecter,<br className="desktop-break"/> vous chauffer et faire grandir vos projets.</p><ButtonLink to="/energies-solutions">Découvrir nos solutions</ButtonLink><div className="hero-local"><MapPin size={16}/><span>Ancrés ici. Engagés pour demain.</span></div></div><div className="hero-image"><img src={media.hero} alt="Lausanne, ses toits et le lac Léman" fetchPriority="high"/><div className="image-label"><span className="label-dot"/> Lausanne, notre énergie commune</div><div className="hero-image-bottom"><span>Tout commence<br/>près de chez vous.</span><ArrowUpRight size={38} strokeWidth={1}/></div></div></section>
  <section className="quick-section container"><div className="quick-heading"><h2>On vous simplifie<br/>le quotidien.</h2><span>Que pouvons-nous faire pour vous ?</span></div><div className="task-grid">{tasks.map(t => <Link key={t.id} to={`/${t.id}`} className="task-card"><t.icon size={25} strokeWidth={1.5}/><span>{t.label}</span><ArrowUpRight size={19}/></Link>)}</div></section>
  <section className="section container"><div className="section-heading"><div><span className="eyebrow">Vos besoins, nos solutions</span><h2>Toutes les énergies<br/>de votre quotidien.</h2></div><Link className="text-link" to="/energies-solutions">Explorer nos solutions<ArrowUpRight size={20}/></Link></div><SolutionGrid/></section>
  <section className="solar-section container"><div className="solar-image"><img src={media.solar} alt="Panneaux photovoltaïques d’une installation solaire lausannoise" loading="lazy"/><span className="photo-tag"><Sun size={17}/>Le soleil travaille pour vous.</span></div><div className="solar-copy"><span className="eyebrow">L’avenir se construit ici</span><h2>Votre toit a<br/>de l’énergie.<br/><span>Révélons-la.</span></h2><p>Produire une énergie locale et renouvelable, ça commence peut-être au-dessus de votre tête. Donnons vie à votre projet solaire.</p><ButtonLink to="/solaire">Passer au solaire</ButtonLink><div className="solar-footnote"><span>Une ressource locale.</span><span>De nouvelles possibilités.</span></div></div></section>
  <section className="section container discover"><div className="section-heading"><div><span className="eyebrow">Ensemble, un pas plus loin</span><h2>L’énergie de changer.</h2></div><Link className="text-link" to="/actualites">À découvrir<ArrowUpRight size={20}/></Link></div><div className="discover-grid"><Link to="/economies-energie" className="discover-card"><div className="discover-art sage"><Leaf size={80} strokeWidth={1}/><span>Moins.<br/>Mais mieux.</span><ArrowUpRight/></div><span className="eyebrow">Les bons gestes</span><h3>Économiser l’énergie,<br/>c’est à la portée de tous.</h3><p>Des conseils concrets pour faire la différence.</p></Link><Link to="/mobilite" className="discover-card"><div className="discover-art blue"><Zap size={80} strokeWidth={1}/><span>En route<br/>vers demain.</span><ArrowUpRight/></div><span className="eyebrow">Mobilité électrique</span><h3>Une nouvelle énergie<br/>pour vos déplacements.</h3><p>Préparez votre projet de recharge.</p></Link><Link to="/les-sil" className="discover-card"><div className="discover-photo"><img src={media.city} alt="Vue de Lausanne" loading="lazy"/><ArrowUpRight/></div><span className="eyebrow">Proches de vous</span><h3>Depuis 1896,<br/>l’énergie des Lausannois.</h3><p>Découvrez les femmes, les hommes et les métiers des SiL.</p></Link></div></section><ContactBanner/></> }
function Breadcrumb({ route }: { route: SiteRoute }) { return <div className="breadcrumb container"><Link to="/">Accueil</Link><ChevronRight size={13}/><span>{route.label}</span></div> }
function Related({ exclude = '' }: { exclude?: string }) { return <section className="related container"><span className="eyebrow">Continuons ensemble</span><h2>À consulter aussi.</h2><div className="related-grid">{siteRoutes.filter(r => ['contact','economies-energie','vos-demarches','solaire'].includes(r.id) && r.id !== exclude).slice(0,3).map(r => <Link key={r.id} to={r.path}><h3>{r.label}</h3><p>{r.description}</p><ArrowUpRight size={24}/></Link>)}</div></section> }
function Interior({ route }: { route: SiteRoute }) {
 const solution = solutions.find(s => s.id === route.id)
 const guide = guides[route.id]
 if (solution) return <><Breadcrumb route={route}/><section className={`offer-hero container ${solution.color}`}><div><span className="eyebrow">Énergies & solutions · {solution.label}</span><h1>{solution.detail}</h1><p>{solution.intro}</p><a className="button" href="#votre-projet">Explorer les possibilités<ArrowRight size={18}/></a></div><div className="offer-symbol">{solution.id === 'solaire' ? <img src={media.solar} alt="Installation photovoltaïque"/> : <><solution.icon strokeWidth={0.8}/><span>{solution.label}<span>Les SiL à vos côtés.</span></span></>}</div></section><section className="section container" id="votre-projet"><span className="eyebrow">Des solutions qui vous ressemblent</span><h2>Votre projet commence ici.</h2><div className="detail-grid">{solution.sections.map(([title, text], i) => <article key={title}><span className="step-number">0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div><Source id={route.id}/></section><ContactBanner/><Related exclude={route.id}/></>
 if (guide) return <><Breadcrumb route={route}/><section className="page-heading container"><span className="eyebrow">{guide.eyebrow}</span><h1>{guide.title}</h1><p>{guide.intro}</p></section><section className="guide-layout container"><div className="steps">{guide.steps.map(([title,text],i) => <article className="guide-step" key={title}><span className="step-number">0{i+1}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}<Source id={route.id}/></div><aside className="help-card"><span className="eyebrow">Bon à savoir</span><h2>Un peu de préparation.<br/>Beaucoup de simplicité.</h2><p>{guide.note}</p><ButtonLink to="/contact">Besoin d’aide ?</ButtonLink></aside></section><Related/></>
 if (route.id === 'energies-solutions') return <><Breadcrumb route={route}/><section className="page-heading container"><span className="eyebrow">L’énergie de toutes vos envies</span><h1>Vos projets.<br/>Nos énergies.</h1><p>Six univers, une même ambition : vous accompagner au quotidien et construire ensemble l’énergie de demain.</p></section><section className="container index-grid"><SolutionGrid/><Source id={route.id}/></section><ContactBanner/></>
 if (route.id === 'vos-demarches') return <><Breadcrumb route={route}/><section className="page-heading container"><span className="eyebrow">Simplement à votre service</span><h1>La bonne démarche.<br/>Au bon endroit.</h1><p>Un déménagement, une facture ou un nouveau projet ? Retrouvez directement les informations dont vous avez besoin.</p></section><section className="container related-grid task-index">{siteRoutes.filter(r=>r.group==='demarches' && r.id !== 'vos-demarches').map(r=><Link to={r.path} key={r.id}><h2>{r.label}</h2><p>{r.description}</p><ArrowUpRight/></Link>)}</section><ContactBanner/></>
 return <><Breadcrumb route={route}/><section className="page-heading container"><span className="eyebrow">{route.id === 'contact' ? 'Proches de vous' : 'Services industriels de Lausanne'}</span><h1>{({ 'les-sil': 'L’énergie d’une ville.\nL’engagement de tous.', 'actualites': 'Demain se prépare\naujourd’hui.', 'economies-energie': 'Moins consommer.\nMieux vivre.', 'carriere': 'Votre talent.\nNotre énergie.', 'contact': 'Faisons avancer\nvotre projet.', 'mentions-legales': 'À propos de\nce prototype.' } as Record<string,string>)[route.id] || route.label}</h1><p>{({ 'les-sil': 'Depuis 1896, les SiL accompagnent la vie lausannoise. Un service public de proximité, au cœur des besoins d’aujourd’hui et des défis de demain.', 'actualites': 'Des sujets à explorer pour comprendre les énergies, préparer vos projets et découvrir les SiL.', 'economies-energie': 'Chaque usage compte. Avec equiwatt, découvrez les gestes et les possibilités pour réduire votre consommation d’énergie.', 'carriere': 'Des métiers concrets, des projets utiles et une ville qui évolue. Découvrez les carrières et la formation au sein des SiL.', 'contact': 'Une question sur votre contrat, un déménagement ou un projet énergétique ? Trouvons ensemble le bon interlocuteur.', 'mentions-legales': 'Une exploration de la présence numérique des Services industriels de Lausanne, réalisée à partir de leurs informations publiques.' } as Record<string,string>)[route.id]}</p></section><InstitutionBody route={route}/>{route.id !== 'mentions-legales' && <Related exclude={route.id}/>}</>
}
function InstitutionBody({ route }: { route: SiteRoute }) {
 if (route.id === 'contact') return <section className="container contact-layout"><article className="address-card"><MapPin size={32} strokeWidth={1.5}/><span className="eyebrow">À Lausanne</span><h2>Rencontrons-nous.</h2><p>Services industriels de Lausanne<br/>Place Chauderon 23<br/>1003 Lausanne</p><a className="button" href={sourceMap.contact || base}>Coordonnées & horaires officiels<ArrowUpRight size={18}/></a></article><div><h2>De quoi avez-vous besoin ?</h2>{tasks.filter(t=>t.id!=='contact').map(t=><Link className="contact-topic" to={`/${t.id}`} key={t.id}><div><h3>{t.label}</h3><p>{t.text}</p></div><ArrowUpRight/></Link>)}<Link className="contact-topic" to="/depannage-urgences"><div><h3>Dépannage & urgences</h3><p>Trouver le service adapté à votre situation</p></div><ArrowUpRight/></Link></div></section>
 if (route.id === 'actualites') return <section className="container actualites-grid">{solutions.filter(s=>['electricite','solaire','mobilite'].includes(s.id)).map(s=><Link key={s.id} to={`/${s.id}`} className={`editorial-card ${s.color}`}><s.icon size={60} strokeWidth={1}/><span className="eyebrow">À découvrir · {s.label}</span><h2>{s.detail}</h2><p>{s.description}</p><ArrowUpRight/></Link>)}<Source id={route.id}/></section>
 if (route.id === 'mentions-legales') return <section className="container legal-copy"><h2>Un prototype de présentation</h2><p>Ce site est un prototype indépendant de refonte de l’interface publique des SiL. Il n’est pas le site officiel de la Ville de Lausanne et ne permet pas de conclure un contrat, d’effectuer un paiement ou de transmettre une demande administrative.</p><h2>Informations et sources</h2><p>Les contenus sont adaptés des pages publiques des Services industriels de Lausanne. Les tarifs, conditions, horaires et coordonnées en vigueur sont à vérifier sur le site officiel. Les liens vers les sources sont accessibles sur les pages concernées.</p><a className="text-link" href={base}>Accéder au site officiel des SiL<ArrowUpRight size={18}/></a><h2>Identité et photographies</h2><p>Le logo SiL et les photographies issues des sites officiels restent la propriété de leurs ayants droit. Leur utilisation dans ce prototype sert uniquement la démonstration d’une proposition d’interface.</p><h2>Vos données</h2><p>Ce prototype ne comporte ni espace de connexion, ni formulaire de collecte. Les démarches personnelles se poursuivent sur les services officiels.</p></section>
 const isAbout = route.id === 'les-sil'
 const blocks = isAbout ? [['Un service public, au quotidien', 'Électricité, chaleur, gaz, multimédia, mobilité et solaire : les SiL réunissent des savoir-faire complémentaires au service de Lausanne et de sa région.'], ['Une histoire qui continue', 'Créés le 4 janvier 1896, les Services industriels de Lausanne accompagnent l’évolution de la ville et les nouveaux besoins de ses habitantes et habitants.'], ['Construire l’énergie de demain', 'Réseaux, production locale, efficacité énergétique : la transition se construit à travers des projets concrets et un accompagnement de proximité.']] : route.id === 'carriere' ? [['Des métiers qui ont du sens', 'Technique, exploitation, ingénierie, relation clientèle ou fonctions de soutien : les activités des SiL font appel à de nombreux métiers.'], ['Apprendre sur le terrain', 'La formation professionnelle permet de transmettre des savoir-faire essentiels. Découvrez les possibilités d’apprentissage proposées par la Ville de Lausanne.'], ['Rejoindre les équipes', 'Les postes et les modalités de candidature sont publiés sur les canaux officiels de la Ville de Lausanne. Consultez-les pour connaître les opportunités disponibles.']] : [['Comprendre ses usages', 'Repérez les équipements et habitudes qui pèsent dans votre consommation. Le chauffage, l’eau chaude et les appareils électriques sont des points de départ utiles.'], ['Adopter les bons gestes', 'Éteindre les appareils inutilisés, ajuster son chauffage et utiliser les équipements à bon escient : commencez par les changements adaptés à votre quotidien.'], ['Découvrir equiwatt', 'Le programme equiwatt des SiL accompagne les économies d’énergie. Retrouvez ses conseils, actions et possibilités de soutien sur le site officiel.']]
 return <><section className="container editorial-feature"><div className={`editorial-visual ${isAbout ? '' : 'sage'}`}>{isAbout ? <img src={media.city} alt="Paysage urbain de Lausanne"/> : route.id === 'carriere' ? <><Zap size={110} strokeWidth={0.8}/><span>Votre métier.<br/>Notre avenir.</span></> : <><Leaf size={110} strokeWidth={0.8}/><span>Chaque geste<br/>a son énergie.</span></>}</div><div>{blocks.map(([title,text])=><article key={title}><h2>{title}</h2><p>{text}</p></article>)}<Source id={route.id}/></div></section><ContactBanner/></>
}
export default function App({ route }: { route: SiteRoute }) { useEffect(() => { document.title = `${route.id === 'home' ? 'L’énergie de Lausanne' : route.label} — SiL` }, [route]); return <><a className="skip-link" href="#main">Aller au contenu</a><Header/><main id="main">{route.id === 'home' ? <Home/> : <Interior route={route}/>}</main><Footer/></> }
