import { Zap, Flame, Sun, Wifi, PlugZap, Leaf, House, FileText, Cable, MessageCircle } from 'lucide-react'

export const base = 'https://www.lausanne.ch/vie-pratique/energies-et-eau/services-industriels'
export const solutions = [
  { id: 'electricite', label: 'Électricité', description: 'Une énergie qui fait vivre votre quotidien.', icon: Zap, color: 'butter', detail: 'Choisissez l’électricité qui vous ressemble.', intro: 'Avec nativa, les SiL proposent une électricité d’origine 100 % renouvelable et vous donnent les clés pour comprendre votre consommation.', sections: [ ['nativa, l’électricité renouvelable', 'Découvrez les variantes du produit nativa et choisissez selon vos critères économiques et environnementaux.'], ['Comprendre les tarifs', 'Le prix de l’électricité comprend notamment l’énergie, l’utilisation du réseau et les taxes. Retrouvez les tarifs en vigueur et leurs explications sur le site officiel.'], ['Mieux suivre sa consommation', 'Comprendre ses usages est un premier pas pour économiser. Retrouvez des conseils pour utiliser votre électricité au quotidien.'] ] },
  { id: 'chaleur', label: 'Chaleur', description: 'Le confort chez vous, la transition en plus.', icon: Flame, color: 'rose', detail: 'Une chaleur locale. Un confort durable.', intro: 'Chauffage à distance ou pompe à chaleur : découvrez les solutions des SiL pour chauffer votre bâtiment et faire évoluer votre installation.', sections: [ ['Le chauffage à distance', 'Un réseau de canalisations transporte la chaleur jusqu’aux bâtiments raccordés. Une solution collective qui accompagne la transition énergétique lausannoise.'], ['Les pompes à chaleur', 'Une pompe à chaleur valorise l’énergie présente dans l’environnement. La solution appropriée dépend des caractéristiques de votre bâtiment et de votre installation.'], ['Préparer votre projet', 'Rénovation ou construction, prenez contact en amont pour étudier les possibilités de raccordement et les solutions adaptées.'] ] },
  { id: 'gaz', label: 'Gaz', description: 'Un accompagnement pour vos besoins en gaz.', icon: Leaf, color: 'sage', detail: 'Votre énergie. Notre accompagnement.', intro: 'Retrouvez les informations sur l’approvisionnement en gaz, les offres et les tarifs, et préparez l’évolution énergétique de votre bâtiment avec les SiL.', sections: [ ['Votre approvisionnement', 'Les SiL distribuent du gaz et vous renseignent sur les produits disponibles et leurs caractéristiques.'], ['Produits et tarifs', 'Les conditions et les prix peuvent évoluer. Consultez les documents officiels pour connaître l’offre applicable à votre situation.'], ['Penser la suite', 'Un changement de chauffage mérite une vue d’ensemble. Explorez également les possibilités de chauffage à distance et de pompe à chaleur.'] ] },
  { id: 'multimedia', label: 'Multimédia', description: 'Toutes vos connexions, tout simplement.', icon: Wifi, color: 'blue', detail: 'bli bla blo, le multimédia d’ici.', intro: 'Internet, télévision et téléphonie : les offres combinées bli bla blo réunissent les services multimédia des SiL dans un abonnement adapté à vos usages.', sections: [ ['Internet à la maison', 'Découvrez les abonnements internet et vérifiez les possibilités disponibles à votre adresse sur le site officiel bli bla blo.'], ['Télévision et téléphonie', 'Composez vos services selon vos usages. Les offres et conditions actuelles sont présentées sur le site officiel.'], ['Besoin d’assistance ?', 'Pour une installation, un changement d’offre ou une difficulté technique, les équipes vous orientent vers le bon service.'] ] },
  { id: 'mobilite', label: 'Mobilité', description: 'De nouvelles façons de prendre la route.', icon: PlugZap, color: 'lavender', detail: 'La mobilité électrique prend sa place.', intro: 'À domicile ou dans vos déplacements, les SiL accompagnent le développement de la mobilité électrique et des solutions de recharge.', sections: [ ['Recharger chez soi', 'L’installation d’une borne se prépare avec les caractéristiques du bâtiment, la puissance disponible et les besoins des utilisateurs.'], ['Un projet collectif', 'Pour une copropriété ou un immeuble, pensez l’infrastructure de recharge à l’échelle du parking et de son évolution.'], ['La recharge au quotidien', 'Retrouvez les informations des SiL sur la mobilité électrique et les services disponibles.'] ] },
  { id: 'solaire', label: 'Solaire', description: 'Faites de votre toit une source d’énergie.', icon: Sun, color: 'peach', detail: 'Votre toit a de l’énergie.', intro: 'Et si votre bâtiment produisait de l’électricité ? Les SiL vous accompagnent pour comprendre le potentiel solaire de votre toit et faire avancer votre projet photovoltaïque.', sections: [ ['Explorer le potentiel de votre toit', 'L’orientation, l’ensoleillement et la surface disponible sont les premiers éléments à examiner pour un projet solaire.'], ['Produire et consommer', 'Une installation photovoltaïque transforme la lumière du soleil en électricité. L’autoconsommation permet d’utiliser sur place une partie de votre production.'], ['Valoriser votre production', 'Raccordement, reprise de l’énergie et démarches : consultez les informations officielles avant de dimensionner votre installation.'] ] },
]
export const tasks = [
  { id: 'demenagement', label: 'Je déménage', text: 'Annoncer mon arrivée ou mon départ', icon: House },
  { id: 'facturation-paiement', label: 'Mes factures', text: 'Comprendre et régler mes factures', icon: FileText },
  { id: 'raccordement', label: 'Mon raccordement', text: 'Préparer un projet pour mon bâtiment', icon: Cable },
  { id: 'contact', label: 'Nous contacter', text: 'Trouver le bon interlocuteur', icon: MessageCircle },
]
export const guides: Record<string, { eyebrow: string; title: string; intro: string; steps: [string,string][]; note: string }> = {
  demenagement: { eyebrow: 'Un nouveau chez-vous', title: 'Vous déménagez ? On vous suit.', intro: 'Vous arrivez à Lausanne, changez de logement ou quittez votre adresse ? Préparez votre annonce pour assurer le suivi de vos contrats.', steps: [['Anticipez votre annonce', 'Annoncez votre arrivée au moins 15 jours ouvrables à l’avance. Préparez aussi votre date de départ si vous quittez un logement.'], ['Rassemblez les informations utiles', 'Gardez à portée de main vos coordonnées, les adresses concernées, les dates et votre référence client si vous en avez une.'], ['Effectuez votre démarche officielle', 'La page officielle des SiL vous oriente vers les formulaires adaptés à une arrivée, un départ ou un changement d’adresse.']], note: 'Vous changez aussi de connexion internet ? Pensez à préparer le transfert de vos services multimédia.' },
  raccordement: { eyebrow: 'Votre bâtiment, nos réseaux', title: 'Raccordons votre projet.', intro: 'Construction, rénovation ou changement de système énergétique : anticipez le raccordement de votre bâtiment avec les SiL.', steps: [['Définissez votre besoin', 'Identifiez les énergies et les services concernés, l’adresse du bâtiment et la nature des travaux envisagés.'], ['Préparez le dossier technique', 'Avec votre mandataire ou votre installateur, réunissez les plans et les caractéristiques de votre projet. Les documents requis dépendent du réseau concerné.'], ['Contactez les équipes des SiL', 'Les équipes vous précisent la procédure, les possibilités techniques et les étapes de raccordement.']], note: 'Un projet solaire ou une borne de recharge peut aussi nécessiter une demande auprès du gestionnaire de réseau.' },
  'facturation-paiement': { eyebrow: 'Votre quotidien, simplifié', title: 'Vos factures, en clair.', intro: 'Retrouvez les informations pour comprendre votre facture d’énergie, suivre votre consommation et connaître les possibilités de paiement.', steps: [['Comprendre votre facture', 'Distinguez les montants liés à votre consommation, aux réseaux et aux taxes. Les explications détaillées figurent dans les informations de facturation des SiL.'], ['Choisir votre mode de paiement', 'Consultez les modes de paiement proposés et leurs conditions sur la page officielle.'], ['Une question sur un montant ?', 'Préparez votre numéro de client et la référence de la facture avant de prendre contact avec les SiL.']], note: 'Vos données personnelles et vos contrats se consultent uniquement dans les services officiels sécurisés.' },
  'depannage-urgences': { eyebrow: 'Besoin d’assistance', title: 'Une panne ? Le bon contact.', intro: 'Électricité, chauffage, gaz ou connexion : identifiez le service concerné pour accéder aux coordonnées de dépannage officielles.', steps: [['Identifiez le service concerné', 'Repérez si la difficulté touche l’électricité, le gaz, le chauffage à distance ou vos services multimédia.'], ['Consultez les contacts officiels', 'La page de dépannage des SiL rassemble les coordonnées et les consignes adaptées à chaque réseau.'], ['Préparez votre signalement', 'Indiquez l’adresse précise et la nature du problème afin de faciliter l’intervention du service concerné.']], note: 'Pour une urgence, utilisez directement les numéros et consignes publiés par les SiL. Ce site de présentation ne reçoit pas de signalements.' },
}
